#!/bin/bash

###
# Geracao de blacklist para MIKROTIK
#
# Autor: Fernando Hallberg <fernando@webgenium.com.br>
#
# Atualizada diariamente as 2:00AM
###

BLACKLIST=/home/blacklist/webgenium-blacklist.rst

WGET=/usr/bin/wget
AGGREGATE=/usr/local/bin/aggregate

echo "ip firewall address-list" > $BLACKLIST
echo "remove [find list=webgenium-blacklist]" >> $BLACKLIST
echo "remove [find list=webgenium-bfb]" >> $BLACKLIST

update()
{
	lista=$1
	url=$2
	delim=" "
	${delim:=$3}

	tmpf=$(mktemp)

#	echo "remove [find list=webgenium-blacklist comment=$lista]" >> $BLACKLIST

	$WGET -q -O$tmpf $url

	cat $tmpf | grep "^[0-9]" | cut -f1 -d"$delim" | grep -v ":"
       	#| while read ip;
	#
	#do
#		echo "add list=webgenium-blacklist address=$ip comment=$lista" >> $BLACKLIST

#	done

	rm -f $tmpf
}

update_cidr()
{
	lista=$1
	url=$2
	cidr=$3

	tmpf=$(mktemp)

#	echo "remove [find list=webgenium-blacklist comment=$lista]" >> $BLACKLIST

	$WGET -q -O$tmpf $url

	cat $tmpf | grep "^[0-9]" | awk '{ print $1 }' | grep -v ":" | while read ip;
	do
		echo $ip/$cidr
#		echo "add list=webgenium-blacklist address=$ip/$cidr comment=$lista" >> $BLACKLIST
#
	done

	rm -f $tmpf
}

blacktmp=$(mktemp)
update SPAMHAUS-DROP http://www.spamhaus.org/drop/drop.txt " " > $blacktmp
update SPAMHAUS-EDROP http://www.spamhaus.org/drop/edrop.txt " " >> $blacktmp
update GREENSNOW https://blocklist.greensnow.co/greensnow.txt >> $blacktmp

update_cidr DSHIELD https://www.dshield.org/block.txt "24" >> $blacktmp
update_cidr TOR https://check.torproject.org/cgi-bin/TorBulkExitList.py?ip=1.2.3.4 "32" >> $blacktmp
update_cidr BLOCKLIST-DE http://lists.blocklist.de/lists/all.txt "32" >> $blacktmp

cat $blacktmp | $AGGREGATE -p 32 | while read ip;
do
		echo "add list=webgenium-blacklist address=$ip" >> $BLACKLIST
done

$WGET -q -O- https://danger.rulez.sk/projects/bruteforceblocker/blist.php | awk '{ print $1; }' | while read ip;
do
		echo "add list=webgenium-bfb address=$ip" >> $BLACKLIST
done

cd /home/blacklist

git commit -a --author="Fernando Hallberg <fernando@webgenium.com.br>" --message="Blacklist Update"
git push
