#!/bin/bash

###
# Geracao de blacklist para MIKROTIK
#
# Autor: Fernando Hallberg <fernando@webgenium.com.br>
#
# Atualizada diariamente as 2:00AM
###

BLACKLIST=/home/blacklist/webgenium-blacklist.rst

WGET=/usr/bin/wget

echo "ip firewall address-list" > $BLACKLIST


update()
{
	lista=$1
	url=$2
	delim=" "
	${delim:=$3}

	tmpf=$(mktemp)

	echo "remove [find list=webgenium-blacklist comment=$lista]" >> $BLACKLIST

	$WGET -q -O$tmpf $url

	cat $tmpf | grep "^[0-9]" | cut -f1 -d"$delim" | while read ip;
	do
		echo "add list=webgenium-blacklist address=$ip comment=$lista" >> $BLACKLIST

	done

	rm -f $tmpf
}
update_cidr()
{
	lista=$1
	url=$2
	cidr=$3

	tmpf=$(mktemp)

	echo "remove [find list=webgenium-blacklist comment=$lista]" >> $BLACKLIST

	$WGET -q -O$tmpf $url

	cat $tmpf | grep "^[0-9]" | awk '{ print $1 }' | while read ip;
	do
		echo "add list=webgenium-blacklist address=$ip/$cidr comment=$lista" >> $BLACKLIST

	done

	rm -f $tmpf
}

update DSHIELD-DROP http://www.spamhaus.org/drop/drop.txt " "
update DSHIELD-EDROP http://www.spamhaus.org/drop/edrop.txt " "
update GREENSNOW https://blocklist.greensnow.co/greensnow.txt

update_cidr DSHIELD https://www.dshield.org/block.txt "24" 
update_cidr TOR https://check.torproject.org/cgi-bin/TorBulkExitList.py?ip=1.2.3.4 "32"
update_cidr BLOCKLIST-DE http://lists.blocklist.de/lists/all.txt "32"

git commit -a --author="Fernando Hallberg <fernando@webgenium.com.br>" --message="Blacklist Update"
git push
