GREENSNOW;https://blocklist.greensnow.co/greensnow.txt
FIREHOL1;https://iplists.firehol.org/files/firehol_level1.netset
FIREHOL2;https://iplists.firehol.org/files/firehol_level2.netset
#FIREHOL3;https://iplists.firehol.org/files/firehol_level3.netset
#FIREHOL4;https://iplists.firehol.org/files/firehol_level4.netset
TOR;https://check.torproject.org/torbulkexitlist?ip=1.2.3.4
#BLOCKLIST-DE;http://lists.blocklist.de/lists/all.txt 
BLOCKLIST-DE;https://lists.blocklist.de/lists/all.txt
BFB;https://danger.rulez.sk/projects/bruteforceblocker/blist.php
CIARMY;http://www.ciarmy.com/list/ci-badguys.txt
HONEYPOT;https://www.projecthoneypot.org/list_of_ips.php?t=d&rss=1
PSBL;rsync://psbl-mirror.surriel.com::psbl/psbl.txt
ABUSEIPDB;https://api.abuseipdb.com/api/v2/blacklist?key=${ABUSEIPDB_KEY}&plaintext
BDS_ATIF;https://www.binarydefense.com/banlist.txt
